@BubberDinner_Api_HostAddress = http://localhost:5171

GET {{BubberDinner_Api_HostAddress}}/dinners/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZTZiMjE2OS1hMDAzLTRlMTUtYWVhYS1iY2IxZGMzYWNmYmUiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiMzkwZWQ5YzgtN2Y5MS00NTMzLTgwYTUtZjQwNjI3ZTJjYzM2IiwiZXhwIjoxNzMxMDExMTcyLCJpc3MiOiJCdWJiZXJEaW5uZXIiLCJhdWQiOiJCdWJiZXJEaW5uZXIifQ.ywwDq_KZBbi1DsxzRE7hglcRHoeiXmmbGfzdoi1f2vA