@BubberDinner_Api_HostAddress = http://localhost:5171

POST {{BubberDinner_Api_HostAddress}}/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email": "johnDoe@hello.com",
  "password": "password"
}
###