@BubberDinner_Api_HostAddress = http://localhost:5171

POST {{BubberDinner_Api_HostAddress}}/auth/register/
Content-Type: application/json
Accept: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johnDoe@hello.com",
  "password": "password"
}

###

